import Head from "next/head";
import Calculator from "../components/Calculator/Calculator";
import Header from "../components/Header/Header";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Most Annoying Calculator Ever...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Calculator */}
      <Calculator />
      {/* Footer */}
    </div>
  );
}
